### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/pow.co#63]
Error message that caused crash was: 
```
GET https://staging-backend.relayx.com/api/market/66 500
```

**Comment by DanielKrawisz** [comment]
More error messages (maybe one of these caused the crash) 
```
TypeError: Cannot read properties of undefined (reading 'item')
    at w (3751-ebb63c4c2d1bfe97.js:1:8683)
    at ak (framework-1f1fb5c07f2be279.js:9:60918)
    at i (framework-1f1fb5c07f2be279.js:9:119476)
    at oD (framework-1f1fb5c07f2be279.js:9:99115)
    at framework-1f1fb5c07f2be279.js:9:98982
    at oO (framework-1f1fb5c07f2be279.js:9:98989)
    at oE (framework-1f1fb5c07f2be279.js:9:95741)
    at oP (framework-1f1fb5c07f2be279.js:9:96130)
    at r8 (framework-1f1fb5c07f2be279.js:9:44779)
    at framework-1f1fb5c07f2be279.js:9:93633
a9 @ framework-1f1fb5c07f2be279.js:9
a.componentDidCatch.t.callback @ framework-1f1fb5c07f2be279.js:9
lW @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
main-5de7dfd2e74ffa18.js:1 TypeError: Cannot read properties of undefined (reading 'item')
    at w (3751-ebb63c4c2d1bfe97.js:1:8683)
    at ak (framework-1f1fb5c07f2be279.js:9:60918)
    at i (framework-1f1fb5c07f2be279.js:9:119476)
    at oD (framework-1f1fb5c07f2be279.js:9:99115)
    at framework-1f1fb5c07f2be279.js:9:98982
    at oO (framework-1f1fb5c07f2be279.js:9:98989)
    at oE (framework-1f1fb5c07f2be279.js:9:95741)
    at oP (framework-1f1fb5c07f2be279.js:9:96130)
    at r8 (framework-1f1fb5c07f2be279.js:9:44779)
    at framework-1f1fb5c07f2be279.js:9:93633
$ @ main-5de7dfd2e74ffa18.js:1
fn @ main-5de7dfd2e74ffa18.js:1
componentDidCatch @ main-5de7dfd2e74ffa18.js:1
a.componentDidCatch.t.callback @ framework-1f1fb5c07f2be279.js:9
lW @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
main-5de7dfd2e74ffa18.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
$ @ main-5de7dfd2e74ffa18.js:1
fn @ main-5de7dfd2e74ffa18.js:1
componentDidCatch @ main-5de7dfd2e74ffa18.js:1
a.componentDidCatch.t.callback @ framework-1f1fb5c07f2be279.js:9
lW @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=lPaX9yMLXkY 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=sKpO4mmtjlA 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
9367-730948921b4a006c.js:1 WebSocket connection to 'wss://tokenmeet.live/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ 9367-730948921b4a006c.js:1
open @ 9367-730948921b4a006c.js:1
open @ 9367-730948921b4a006c.js:1
te @ 9367-730948921b4a006c.js:1
open @ 9367-730948921b4a006c.js:1
(anonymous) @ 9367-730948921b4a006c.js:1
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/boostpow-api/items/issues 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/www.sonicboost.club 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/erc721.ts 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/scryptTS-examples/items/blob 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=WABEU3YUsdc 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=LCxuFWVTxfk 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=H9M5vC0WhHQ 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=kjxSCAalsBE 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/Conan-2.0.html 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/2023/items/02 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/90h7Pzaoys8 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/watch?v=l4fftDJGXK4 500
(anonymous) @ _app-716bd5a1f586c2f4.js:14
xhr @ _app-716bd5a1f586c2f4.js:14
eG @ _app-716bd5a1f586c2f4.js:14
request @ _app-716bd5a1f586c2f4.js:14
(anonymous) @ _app-716bd5a1f586c2f4.js:14
i @ 3751-ebb63c4c2d1bfe97.js:1
i @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
(anonymous) @ 9734-fc75f978fb695764.js:9
uU @ framework-1f1fb5c07f2be279.js:9
uX @ framework-1f1fb5c07f2be279.js:9
e @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
oU @ framework-1f1fb5c07f2be279.js:9
oP @ framework-1f1fb5c07f2be279.js:9
r8 @ framework-1f1fb5c07f2be279.js:9
(anonymous) @ framework-1f1fb5c07f2be279.js:9
_app-716bd5a1f586c2f4.js:14          GET https://staging-backend.relayx.com/api/market/Zvi4JYmRXzI 500
```

**Comment by 1aristotelis** [comment]
should be ok now. Still need to improve how we display run items / onchain orderlocks but that's another issue
